### ISSUE TITLE
Automatic code quality checks for Python?

### ISSUE THREAD

**Issue by bittner** [tourdedave/elemental-selenium-tips#26]
Should we add checks on code quality that are automatically run each time changes are applied?

For Python, this would merely be running the tools [Flake8](http://flake8.pycqa.org/) and [Pylint](http://pylint.readthedocs.io/) in a Travis-CI configuration file, e.g.
```yaml
# FILE: .travis.yml
language: python
python:
  - 3.6
before_script:
  - pip install flake8 pylint
script:
  - flake8 */python
  - pylint */python/*.py
```

This could (later) be extended to other languages. I would then suggest to use Travis' [build stages feature](https://docs.travis-ci.com/user/build-stages) to beautifully organize - visually separate, really - the linter results for the separate languages.
